source 'https://rubygems.org'

gem 'builder'
gem 'mime-types'
gem 'systemu'
gem 'rack'
gem 'adsf'
gem 'albino'
gem 'compass', '~> 1.0.alpha'
gem 'breakpoint'
gem 'sass'
gem 'susy'
gem 'nanoc'
gem 'guard-nanoc'
gem 'summarize'
gem 'nanoc-toolbox'
gem 'kramdown'
gem 'rake'
gem 'slim'
gem 'pygments.rb'
gem 'psych'
gem 'nokogiri'
gem 'listen'
gem 'stringex'
gem 'org-ruby'
